from enum import Enum


class TIPO(Enum):
  PAIS = 1
  COMPETICAO = 2
  EQUIPE = 3
  PARTIDA = 4
  EDICAO_COMPETICAO = 5


class STATUS(Enum):
  EXTRACAO_COMPETICOES = 1
  EXTRACAO_PARTIDAS = 2
  AGUARDANDO_EXTRACAO = 3
  ERRO = 4
  OK = 5
  PROCESSANDO = 6
  EXTRACAO_EQUIPES = 7
  EXTRACAO_EDICOES_COMPETICAO = 8
  ERRO_EXTRACAO_EQUIPES = 9
  ERRO_EXTRACAO_PARTIDAS = 10