from enum import Enum

class TIPO(Enum):
  EXTRACAO_PARTIDAS_DIA = 1
  ATUALIZACAO_PARTIDAS_DIA = 2
  ATUALIZACAO_PARTIDAS_ANTIGAS_NAO_FINALIZADAS = 3

class STATUS(Enum):
  NAO_INICIADO = 1
  EM_PROCESSAMENTO = 2
  FINALIZADO = 3
  ERRO = 4